version: "3.5"

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: api
    command: npm start
    ports:
      - 1209:1209
    volumes:
      - ./Api:/app
        - /Api/node_modules
    env_file:
      - ./Api/.env
  app:
    image: lequyvu2001/admin:latest
    container_name: app
    environment:
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=1038867842546-08nb3bfjvnn7os20jqsr24nq1hgc0diq.apps.googleusercontent.com
      - NEXT_PUBLIC_GOOGLE_CLIENT_SECRET=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
      - NEXT_PUBLIC_NEXTAUTH_SECRET=EscLg7T59CgKzF1
      - NEXT_PUBLIC_NEXTAUTH_URL=http://short.zinza.com.vn
      - NEXT_PUBLIC_API_URL=http://short.zinza.com.vn/api-v1/
      - NEXT_PUBLIC_URL_CDN=http://short.zinza.com.vn/cdn-v1/
    ports:
      - 3000:3000

  redis:
    container_name: redis
    image: redis
    command:
      [
        "redis-server",
        "--appendonly",
        "no",
        "--maxmemory",
        "500mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - api
      - app
volumes:
  mongodb_data:
  redis_data:
