version: "3.8"

services:
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    container_name: api-phim
    command: npm start
    ports:
      - 1209:1209
    volumes:
      - ./Api:/app
        - /Api/node_modules
    env_file:
      - ./Api/.env
    networks:
      - app-network

  admin:
    build:
      context: ./Admin
      dockerfile: Dockerfile
    container_name: admin-phim
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./Admin:/app
      # - /Admin/node_modules
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis
    command:
      [
        "redis-server",
        "--appendonly",
        "no",
        "--maxmemory",
        "500mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    environment:
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - api
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongodb_data:
  redis_data:
